<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign In ! </title>
</head>
<body>
<h1>Sign In !</h1>
<div>
    <form action="/signInChat" method="post">
        <input name="email" placeholder="Email">
        <input type="password" name="password" placeholder="password">
        <input type="submit" value="Submit">
    </form>
</div>
</body>
</html>
