<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data" action="">
        File to upload: <input type="file" name="file"><br/>
        Email: <input type="email" name="email"><br/>
        Name: <input type="text" name="name"><br/> <br/>
        <input type="submit" value="sss"> Press here to upload the fileModel!
    </form>
</body>
</html>